# Generated by Django 4.1.1 on 2022-10-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_compta'),
    ]

    operations = [
        migrations.AddField(
            model_name='compta',
            name='drf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
